site_name: Özcan Yarımdünya
site_url: https://yarimdunya.com
site_author: Özcan Yarımdünya
site_description: Özcan Yarımdünya
repo_name: yarimdunya.com
repo_url: https://github.com/ozcanyarimdunya/yarimdunya.com

copyright: Copyright &copy; 2022 <a href="https://yarimdunya.com" target="_blank">Özcan Yarımdünya<a/>

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  custom_dir: theme
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: assets/images/favicon.ico
  icon:
    logo: svg/favicon
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ozcanyarimdunya
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ozcanyarimdunya
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ozcanyarimdunya
      name: Github
    - icon: material/gmail
      link: mailto:ozcanyd@gmail.com
      name: Mail
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/3117592/ozcanyarimdunya
      name: Stack Overflow
